import sys
sys.path.insert(0,sys.argv[2])
import mock
from playwright.sync_api import sync_playwright
F=sys.argv[1];OUT=sys.argv[3];fails=[]
def chk(n,c,info=""):
    print(("PASS " if c else "FAIL ")+n+(" — "+str(info) if info!="" else ""));(not c) and fails.append(n)
def route(pg):pg.route("**/*",lambda r:r.continue_() if r.request.url.startswith(("file:","data:","blob:")) else mock.handle(r))
with sync_playwright() as p:
    b=p.chromium.launch()
    ctx=b.new_context(viewport={"width":1500,"height":1000},permissions=["clipboard-read","clipboard-write"]);pg=ctx.new_page();errs=[];pg.on("pageerror",lambda e:errs.append(str(e)));route(pg)
    pg.add_init_script("localStorage.setItem('lm_user','xParRaidr');localStorage.setItem('lm_tab','s')")
    pg.goto(F);pg.wait_for_timeout(5000)
    chk("saved Survivor tab falls back to Matchups when not linked",pg.evaluate("S.tab")=="m")
    chk("nav = Matchups, Radar (BETA), Lab (Edge hidden until unlocked)",pg.evaluate("[...document.querySelectorAll('header .tabs > .tb')].filter(b=>b.style.display!=='none').map(b=>b.innerText.replace(/\\s+/g,' ')).join('|')")=="🏈 Matchups|📡 RadarBETA|🧠 Lab",pg.evaluate("[...document.querySelectorAll('header .tabs > .tb')].filter(b=>b.style.display!=='none').map(b=>b.innerText).join('|')"))
    chk("chips: no fade when nothing overflows",not pg.evaluate("document.getElementById('lgs').classList.contains('ovf')"))
    chk("no 🔥/🧊 on matchup cards while some teams are at 0",pg.evaluate("document.querySelectorAll('.lg .mini .tbg').length")==0)
    chk("rows 36px / header 1 row",set(pg.evaluate("[...document.querySelectorAll('.lg .card.tw:not(.benchcard) tr.pr')].map(r=>Math.round(r.getBoundingClientRect().height))"))=={36} and pg.evaluate("Math.round(document.querySelector('header').getBoundingClientRect().height)")<=48)
    chk("photos back to v36 crop",pg.evaluate("!document.querySelector('.avc')&&getComputedStyle(document.querySelector('.lg .avw .av')||document.body).transform!=='matrix(1.5, 0, 0, 1.5, 0, 0)'"))
    # red zone: effect behind text
    r=pg.evaluate("""(()=>{const td=document.querySelector('.lg td[data-pos=TE]:not(.r)');playEventAnimation('rz',td,{side:'R'});const fx=td.querySelector(':scope>.fx'),pc=td.querySelector(':scope>.pc');return [getComputedStyle(fx).zIndex,getComputedStyle(pc).zIndex,getComputedStyle(pc).position]})()""")
    chk("red zone animation sits behind the text",r==["0","1","relative"],r)
    # bench live re-sort
    od=lambda:pg.evaluate("[...document.querySelector('.lg .benchcard').querySelectorAll('tr.pr td[data-pos]:not(.r) .fnm')].map(x=>x.textContent).join('|')")
    b0=od();mock.NYG_LIVE[0]=True;mock.LIVE["800"]=dict(rush_att=15,rush_yd=140,rush_td=2);pg.wait_for_timeout(7000)
    chk("bench re-sorts live without reload",od().startswith("Rookie Back") and not b0.startswith("Rookie Back"),b0+" → "+od())
    # Lab: one Power & IQ board with awards
    pg.click('header .tb[data-t="t"]');pg.wait_for_timeout(6000)
    chk("Lab sections: Power & IQ + Trades",pg.evaluate("[...document.querySelectorAll('#moves .svh')].map(x=>x.innerText.replace(/^[▾▸]/,'').split('\\n')[0].trim()).join('|')").startswith("🏆 Rankings & IQ|🤝 Trades"),pg.evaluate("[...document.querySelectorAll('#moves .svh')].map(x=>x.innerText.split('\\n')[0]).join('|')"))
    print("     awards:",pg.evaluate("[...document.querySelectorAll('#moves .awd')].map(a=>a.innerText.replace(/\\n/g,' ')).join(' || ')"))
    print("     rows:",pg.evaluate("[...document.querySelectorAll('#moves .pwt tbody tr')].slice(0,3).map(r=>r.innerText.replace(/\\s+/g,' ')).join(' || ')"))
    chk("blunder is real (bench pts > starter pts, same lineup family)",pg.evaluate("""(()=>{const Q=MV.iq[S.L[0].id];return Q.rows.filter(r=>r.blunder).every(r=>r.blunder.bp>r.blunder.sp)})()"""))
    pg.click('#moves th.srt[data-sort="iq"]');pg.wait_for_timeout(300)
    effs=pg.evaluate("[...document.querySelectorAll('#moves .pwt tbody tr .iqr b')].map(b=>+b.textContent)")
    chk("sort by IQ works",effs==sorted(effs,reverse=True),effs)
    pg.click("#iqroast");pg.wait_for_timeout(300);txt=pg.evaluate("navigator.clipboard.readText()")
    chk("copy roast for group chat",txt.startswith("🧠 WINGMAN LINEUP IQ"),txt[:200].replace("\n"," / "))
    chk("trades header links to Sleeper trades",pg.evaluate("(document.querySelector('#moves .trl2')||{}).href")=="https://sleeper.com/leagues/L1/trades")
    chk("secret Waiver edge link still there",pg.evaluate("!!document.getElementById('mvedge')"))
    pg.screenshot(path=OUT+"/lab38.png",full_page=True)
    # Survivor via Google Sheet connection
    pg.click("#who");pg.wait_for_timeout(200)
    chk("MFL / Fleaflicker cards replaced",pg.evaluate("[...document.querySelectorAll('.pcard .pname')].map(x=>x.innerText).join('|')")=="Sleeper|ESPN Fantasy|Yahoo Fantasy|Survivor Pool|Pick'em|Custom Import",pg.evaluate("[...document.querySelectorAll('.pcard .pname')].map(x=>x.innerText).join('|')"))
    pg.click('.pcard[data-p=survivor] .pcta');pg.fill("#shurl","nope");pg.click("#shgo");pg.wait_for_timeout(150)
    chk("bad link rejected",pg.evaluate("document.getElementById('werr').innerText").startswith("That doesn't look"))
    pg.fill("#shurl","https://docs.google.com/spreadsheets/d/SURVtestsheet0000000000001/edit#gid=0");pg.click("#shgo");pg.wait_for_timeout(2500)
    chk("Survivor tab appears once linked",pg.evaluate("document.querySelector('header .tb[data-t=\"s\"]').style.display")=="")
    chk("Pick'em still hidden",pg.evaluate("document.querySelector('header .tb[data-t=\"p\"]').style.display")=="none")
    pg.click('#wback');pg.click('header .tb[data-t="s"]');pg.wait_for_timeout(1500)
    pg.wait_for_timeout(1500);chk("Survivor asks whose entries, then renders",pg.is_visible("#svme"));pg.select_option("#svme","Our Group");pg.click("#svmego");pg.wait_for_timeout(800);chk("Survivor dashboard renders",pg.evaluate("document.querySelectorAll('#surv .card').length")>2)
    chk("no errors desktop",not errs,errs[:3])
    ctx.close()
    m=b.new_page(viewport={"width":390,"height":844},is_mobile=True,has_touch=True);e2=[];m.on("pageerror",lambda e:e2.append(str(e)));route(m)
    m.add_init_script("localStorage.setItem('lm_user','xParRaidr');localStorage.setItem('lm_tab','m')");m.goto(F);m.wait_for_timeout(5000)
    chk("phone: no horizontal scroll",m.evaluate("document.documentElement.scrollWidth")<=390)
    chk("phone: bottom bar Matchups/Field/Lab",m.evaluate("[...document.querySelectorAll('.tabs > .tb')].filter(b=>b.style.display!=='none').length")==3)
    m.locator('.tabs .tb[data-t="t"]').tap();m.wait_for_timeout(5000)
    chk("phone: Lab board scrolls inside its card, page doesn't",m.evaluate("document.documentElement.scrollWidth")<=390)
    m.screenshot(path=OUT+"/lab38m.png")
    chk("no errors phone",not e2,e2[:3])
    b.close()
print("\nFAILED:",fails)
